# =============================================================================
# Variables for the GreetEat Paperclip prod environment.
# =============================================================================
# Values are set in terraform.tfvars (committed) and versions.tfvars
# (committed; updated on each Paperclip image promotion).

# -----------------------------------------------------------------------------
# Project & region
# -----------------------------------------------------------------------------

variable "project_id" {
  type        = string
  description = "GCP project ID. Must be paperclip-492823 for this deployment."

  validation {
    condition     = var.project_id == "paperclip-492823"
    error_message = "This deployment is locked to the dedicated paperclip-492823 project."
  }
}

variable "region" {
  type        = string
  description = "GCP region for all regional resources."
  default     = "us-central1"
}

# -----------------------------------------------------------------------------
# Public hostname for the deployment
# -----------------------------------------------------------------------------

variable "domain" {
  type        = string
  description = "Public hostname Paperclip is reachable at (e.g. paperclip.greeteat.example). Operator must set the actual value in terraform.tfvars."
}

# -----------------------------------------------------------------------------
# Cloud SQL sizing (used by module.database in Phase 3)
# -----------------------------------------------------------------------------

variable "cloud_sql_tier" {
  type        = string
  description = "Cloud SQL machine tier for paperclip-pg."
  default     = "db-custom-2-7680"
}

variable "cloud_sql_availability_type" {
  type        = string
  description = "Cloud SQL availability type. MUST be REGIONAL for the single-env production deployment."
  default     = "REGIONAL"

  validation {
    condition     = var.cloud_sql_availability_type == "REGIONAL"
    error_message = "Single-env deployment treats prod as production; Cloud SQL must be REGIONAL (HA)."
  }
}

variable "cloud_sql_backup_retention_days" {
  type        = number
  description = "Number of days of point-in-time recovery to retain on paperclip-pg."
  default     = 7
}

# -----------------------------------------------------------------------------
# Cloud Run sizing (used by module.compute in Phase 3)
# -----------------------------------------------------------------------------

variable "cloud_run_min_instances" {
  type        = number
  description = "Cloud Run min-instances for the paperclip service. MUST be >= 2 (always warm, no cold-start drain on rolling deploys)."
  default     = 2

  validation {
    condition     = var.cloud_run_min_instances >= 2
    error_message = "Single-env deployment requires min-instances >= 2 to avoid cold starts and rolling-deploy drains."
  }
}

variable "cloud_run_max_instances" {
  type        = number
  description = "Cloud Run max-instances ceiling for the paperclip service."
  default     = 10
}

variable "cloud_run_cpu" {
  type        = string
  description = "Cloud Run CPU allocation per instance."
  default     = "2"
}

variable "cloud_run_memory" {
  type        = string
  description = "Cloud Run memory allocation per instance."
  default     = "2Gi"
}

# -----------------------------------------------------------------------------
# Cost ceiling (used by module.observability for budget alerts in Phase 8)
# -----------------------------------------------------------------------------

variable "monthly_budget_usd" {
  type        = number
  description = "Monthly cost ceiling in USD. Cloud Billing budget alert fires before forecasted spend reaches this value (FR-027)."

  validation {
    condition     = var.monthly_budget_usd > 0
    error_message = "Monthly budget must be a positive USD value declared by the operator."
  }
}

# -----------------------------------------------------------------------------
# Pinned Paperclip version + image digest (set in versions.tfvars)
# -----------------------------------------------------------------------------

variable "paperclip_version" {
  type        = string
  description = "Pinned Paperclip release tag (e.g. v0.42.0). The image build workflow clones Paperclip at this tag. Bumped via PR; the corresponding paperclip_image_digest is updated in the same PR."
}

variable "paperclip_image_digest" {
  type        = string
  description = "Immutable Artifact Registry image digest (sha256:...) for the paperclip_version above. Generated by .github/workflows/build-image.yml after the version bump and pinned here. Terraform consumes the digest, never a tag."

  validation {
    condition     = can(regex("^sha256:[a-f0-9]{64}$", var.paperclip_image_digest)) || var.paperclip_image_digest == "TBD"
    error_message = "paperclip_image_digest must match sha256:<64 hex chars>. Set to 'TBD' only as an initial placeholder before the first build."
  }
}
